FROM amazoncorretto:21.0.4-alpine3.18

WORKDIR /app

ENV PORT_FARMA=${PORT_FARMA}
ENV DB_URL=${DB_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV FRONT_URL=${FRONT_URL}
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

COPY target/FarmaNear-Register-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]